In [2]:
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service
import pandas as pd
import time

from datetime import datetime
import time
import pandas as pd
from selenium import webdriver

In [3]:

def get_coin_data(driver, coin):
    url = f'https://www.bitget.com/price/{coin}'
    driver.get(url)
    time.sleep(2)
    try:
        labels = driver.find_elements(By.XPATH, '//span[@class="text-[14px] text-[var(--content-secondary)]"]')
        values = driver.find_elements(By.XPATH, '//span[@class="text-[14px] font-[600]"]')
        price=driver.find_element(By.XPATH,'//span[@class="font-bold text-[40px] ltIpad:text-[32px] leading-[48px] ltIpad:leading-[38px] text-primaryText"]').text
        date=driver.find_element(By.XPATH,'//div[@class="text-[14px] mt-[24px] text-thirdText font-medium"]').text
        keys = [el.text.replace(':', '').strip() for el in labels]
        vals = [el.text.replace('\n', '').strip() for el in values]
        limit = min(len(keys), len(vals))
        data = {keys[i]: vals[i] for i in range(limit)}
        data['coin'] = coin  
        data['price'] = price
        data['date'] = date
        return data
    except Exception as e:
        print(f"Lỗi khi lấy dữ liệu {coin}: {e}")
        return {'coin': coin, 'error': str(e)}
list_coin=['bitcoin','ethereum','binance','solana','ripple','cardano',
'avalanche','polkadot','chainlink','tron']
driver = webdriver.Chrome()
all_data = [get_coin_data(driver, coin) for coin in list_coin]
driver.quit()
df = pd.DataFrame(all_data)

In [4]:

from datetime import datetime
import re
df['collection_timestamp'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')


def extract_date(date_string):
    try:
        date_pattern = r'(\w+ \d+, \d{4})'
        match = re.search(date_pattern, date_string)
        if match:
            parsed_date = datetime.strptime(match.group(1), '%B %d, %Y')
            return parsed_date.strftime('%Y-%m-%d')
        return None
    except Exception:
        return None

df['parsed_date'] = df['date'].apply(extract_date)
df_improved = df.copy()
priority_columns = ['coin', 'price', 'date', 'parsed_date', 'collection_timestamp']
other_columns = [col for col in df_improved.columns if col not in priority_columns and col != 'error']
if 'error' in df_improved.columns:
    df_improved = df_improved[priority_columns + other_columns + ['error']]
else:
    df_improved = df_improved[priority_columns + other_columns]
df_improved.set_index('coin', inplace=True)

In [5]:
df_improved

,price,date,parsed_date,collection_timestamp,Market cap,Fully diluted market cap,Volume (24h),24h volume / market cap,24h high,24h low,...,Circulating supply,Total supply,Circulation rate,Max supply,Price in BTC,Price in ETH,Price at BTC market cap,Price at ETH market cap,Contracts,Links
coin,,,,,,,,,,,,,,,,,,,,,
bitcoin,"$103,458.61",Last updated as of 2025-05-31 02:09:57（UTC+0）,None,2025-05-31 09:12:05,"$2,055,961,718,600.79","$2,055,961,718,600.79","$56,092,435,961.41",2.72%,"$106,308.95","$103,519.31",...,"19,872,312 BTC","19,872,312BTC",100.00%,"21,000,000BTC",1 BTC,41.54 ETH,"$103,458.61","$15,131.69",--,
ethereum,"₫64,977,185.75",Last updated as of 2025-05-31 02:11:22（UTC+0）,None,2025-05-31 09:12:05,"₫7,844,306,690,033,009","₫7,844,306,690,033,009","₫647,278,647,179,300.8",8.25%,"₫68,911,286.79","₫64,642,613.79",...,"120,724,010 ETH","120,724,006.99ETH",100.00%,--ETH,0.02410 BTC,1 ETH,"₫443,806,243.82","₫64,977,185.75",0xeeee...eeeeeee(Arbitrum)More,
binance,"₫16,859,876.72",Last updated as of 2025-05-31 02:11:27（UTC+0）,None,2025-05-31 09:12:05,"₫2,375,349,458,713,217.5","₫2,375,349,458,713,217.5","₫49,021,409,588,292.88",2.06%,"₫17,548,039.63","₫16,842,831.45",...,"140,887,710 BNB","140,887,709.6BNB",100.00%,--BNB,0.006253 BTC,0.2595 ETH,"₫380,289,170.95","₫55,677,720.72",0xeeee...eeeeeee(BNB Smart Chain (BEP20))More,
solana,"₫4,001,062.53",Last updated as of 2025-05-31 02:11:31（UTC+0）,None,2025-05-31 09:12:05,"₫2,089,727,985,289,803","₫2,089,727,985,289,803","₫111,355,390,720,967.84",5.32%,"₫4,313,381.3","₫3,978,935.54",...,"522,293,250 SOL","601,973,901.32SOL",86.00%,--SOL,0.001484 BTC,0.06158 ETH,"₫102,582,352.69","₫15,018,969.83",So1111...1111111(Solana)More,
ripple,"₫55,096.76",Last updated as of 2025-05-31 02:11:35（UTC+0）,None,2025-05-31 09:12:05,"₫3,237,470,468,492,817.5","₫3,237,470,468,492,817.5","₫91,272,914,249,000.8",2.81%,"₫58,019.99","₫54,925.57",...,"58,759,725,000 XRP","99,986,084,900XRP",58.00%,--XRP,0.{4}2044 BTC,0.0008479 ETH,"₫911,816.26","₫133,498.02",0x1d2f...6c60dbe(BNB Smart Chain (BEP20))More,
cardano,"₫17,499.38",Last updated as of 2025-05-31 02:11:39（UTC+0）,None,2025-05-31 09:12:05,"₫618,388,463,704,178.6","₫618,388,463,704,178.6","₫23,561,457,098,494.41",3.81%,"₫18,569.72","₫17,453.22",...,"35,337,744,000 ADA","44,994,501,828.19ADA",78.00%,--ADA,0.{5}6491 BTC,0.0002693 ETH,"₫1,516,171.24","₫221,980.97",0x3ee2...d435d47(BNB Smart Chain (BEP20))More,
avalanche,"₫522,947.16",Last updated as of 2025-05-31 02:11:43（UTC+0）,None,2025-05-31 09:12:05,"₫220,419,624,171,186.78","₫220,419,624,171,186.78","₫14,388,889,664,161.59",6.52%,"₫568,940.76","₫519,658.95",...,"421,495,000 AVAX","456,497,722.74AVAX",92.00%,"715,748,719AVAX",0.0001940 BTC,0.008048 ETH,"₫127,114,363.54","₫18,610,674.65",FvwEAh...GCgxN5Z(Avalanche X-Chain)More,
polkadot,"₫102,994.12",Last updated as of 2025-05-31 02:11:48（UTC+0）,None,2025-05-31 09:12:05,"₫163,008,321,517,789.97","₫163,008,321,517,789.97","₫7,533,703,496,697.08",4.62%,"₫110,209.89","₫102,291.46",...,"1,582,695,400 DOT","1,582,695,367.35DOT",100.00%,--DOT,0.{4}3820 BTC,0.001585 ETH,"₫33,852,421.22","₫4,956,295.89",0x7083...c873402(BNB Smart Chain (BEP20))More,
chainlink,"₫355,188.9",Last updated as of 2025-05-31 02:11:52（UTC+0）,None,2025-05-31 09:12:05,"₫233,394,616,965,782.2","₫233,394,616,965,782.2","₫15,778,373,012,081.22",6.76%,"₫383,807.06","₫353,531.99",...,"657,099,970 LINK","1,000,000,000LINK",65.00%,--LINK,0.0001317 BTC,0.005466 ETH,"₫81,537,167.44","₫11,937,767.32",0xf97f...8539FB4(Arbitrum)More,
tron,"₫6,866.04",Last updated as of 2025-05-31 02:11:56（UTC+0）,None,2025-05-31 09:12:05,"₫651,355,987,958,629.8","₫651,355,987,958,629.8","₫21,056,757,113,624.13",3.23%,"₫7,110.09","₫6,859.14",...,"94,866,290,000 TRX","94,866,289,321.02TRX",100.00%,--TRX,0.{5}2547 BTC,0.0001057 ETH,"₫564,774.58","₫82,688.03",0xCE7d...C6b12e3(BNB Smart Chain (BEP20))More,

In [6]:

if 'Market Cap' in df.columns:
    
    def convert_market_cap(value):
        if pd.isna(value):
            return None
        value = value.replace('$', '').replace(',', '')
        
        multiplier = 1
        if value.endswith('B'):
            multiplier = 1_000_000_000
            value = value[:-1]
        elif value.endswith('M'):
            multiplier = 1_000_000
            value = value[:-1]
        elif value.endswith('K'):
            multiplier = 1_000
            value = value[:-1]
            
        try:
            return float(value) * multiplier
        except:
            return None
    
    df['market_cap_value'] = df['Market Cap'].apply(convert_market_cap)
    
    
    market_cap_df = df.sort_values('market_cap_value', ascending=False)
    try:
        import matplotlib.pyplot as plt
        plt.figure(figsize=(12, 6))
        plt.bar(market_cap_df['coin'], market_cap_df['market_cap_value'])
        plt.title('Market Cap của các đồng tiền điện tử')
        plt.xlabel('Đồng tiền')
        plt.ylabel('Market Cap (USD)')
        plt.xticks(rotation=45)
        plt.tight_layout()
        plt.show()
    except Exception as e:
        print(f"Không thể hiển thị biểu đồ: {e}")
        print("Dữ liệu Market Cap theo thứ tự giảm dần:")
        print(market_cap_df[['coin', 'Market Cap', 'market_cap_value']])

In [11]:
def update_crypto_data_single_df(interval_minutes=5, max_updates=10):
    """
    Cập nhật dữ liệu tiền điện tử theo định kỳ mỗi phút vào một DataFrame duy nhất
    
    interval_minutes: Thời gian giữa các lần cập nhật (phút)
    max_updates: Số lần cập nhật tối đa
    """
    print(f"Bắt đầu thu thập dữ liệu mỗi {interval_minutes} phút, tối đa {max_updates} lần")
    
    # Định nghĩa hàm extract_date bên trong để đảm bảo nó luôn khả dụng
    def extract_date(date_string):
        try:
            date_pattern = r'(\w+ \d+, \d{4})'
            match = re.search(date_pattern, date_string)
            if match:
                parsed_date = datetime.strptime(match.group(1), '%B %d, %Y')
                return parsed_date.strftime('%Y-%m-%d')
            return None
        except Exception:
            return None
    
    driver = webdriver.Chrome()
    
    # Tạo DataFrame rỗng ban đầu
    master_df = pd.DataFrame()
    
    try:
        for i in range(max_updates):
            current_time = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            print(f"Đang cập nhật lần {i+1}/{max_updates} tại {current_time}...")
            
            # Thu thập dữ liệu mới
            current_data = [get_coin_data(driver, coin) for coin in list_coin]
            
            # Thêm timestamp và số lần cập nhật
            timestamp = datetime.now().strftime('%Y-%m-%d %H:%M:%S')
            for data in current_data:
                data['collection_timestamp'] = timestamp
                data['update_number'] = i+1
            
            # Tạo DataFrame từ dữ liệu hiện tại
            temp_df = pd.DataFrame(current_data)
            
            # Cải thiện trình bày dữ liệu
            temp_df['parsed_date'] = temp_df['date'].apply(extract_date)
            
            # Thêm dữ liệu mới vào DataFrame chính
            if master_df.empty:
                master_df = temp_df.copy()
            else:
                master_df = pd.concat([master_df, temp_df], ignore_index=True)
            
            # Hiển thị thông tin ngắn gọn
            print(f"Cập nhật lần {i+1} hoàn tất. Tổng số bản ghi hiện tại: {len(master_df)}")
            print("Giá hiện tại:")
            for data in current_data:
                print(f"{data['coin']}: {data['price']}")
            print("-" * 50)
            
            if i < max_updates - 1:
                # Đợi đến lần cập nhật tiếp theo
                print(f"Đợi {interval_minutes} phút cho lần cập nhật tiếp theo...")
                time.sleep(interval_minutes * 60)
    
    except KeyboardInterrupt:
        print("Người dùng đã dừng quá trình thu thập dữ liệu")
    except Exception as e:
        print(f"Lỗi khi cập nhật dữ liệu: {e}")
    
    finally:
        driver.quit()
        print("Đã đóng trình duyệt")
    
    print(f"Hoàn tất thu thập dữ liệu. Tổng số bản ghi: {len(master_df)}")
    
    return master_df

# Chạy hàm thu thập dữ liệu mỗi 1 phút với một DataFrame duy nhất
updated_data = update_crypto_data_single_df(interval_minutes=5, max_updates=10)

Bắt đầu thu thập dữ liệu mỗi 5 phút, tối đa 10 lần

KeyboardInterrupt:

In [9]:
updated_data

,Market cap,Fully diluted market cap,Volume (24h),24h volume / market cap,24h high,24h low,All-time high,All-time low,Circulating supply,Total supply,...,Price at BTC market cap,Price at ETH market cap,Contracts,Links,coin,price,date,collection_timestamp,update_number,parsed_date
0,"$2,055,961,718,600.79","$2,055,961,718,600.79","$56,092,435,961.41",2.72%,"$106,308.95","$103,519.31","$111,970.17",$0.04865,"19,872,312 BTC","19,872,312BTC",...,"$103,458.61","$15,131.69",--,,bitcoin,"$103,458.61",Last updated as of 2025-05-31 02:09:57（UTC+0）,2025-05-31 09:12:40,1,None
1,"₫7,844,306,690,033,009","₫7,844,306,690,033,009","₫647,278,647,179,300.8",8.25%,"₫68,911,286.79","₫64,642,613.79","₫127,288,698.79","₫10,952.3","120,724,010 ETH","120,724,006.99ETH",...,"₫443,806,243.82","₫64,977,185.75",0xeeee...eeeeeee(Arbitrum)More,,ethereum,"₫64,977,185.75",Last updated as of 2025-05-31 02:11:22（UTC+0）,2025-05-31 09:12:40,1,None
2,"₫2,375,349,458,713,217.5","₫2,375,349,458,713,217.5","₫49,021,409,588,292.88",2.06%,"₫17,548,039.63","₫16,842,831.45","₫20,644,041.51","₫2,500.9","140,887,710 BNB","140,887,709.6BNB",...,"₫380,289,170.95","₫55,677,720.72",0xeeee...eeeeeee(BNB Smart Chain (BEP20))More,,binance,"₫16,859,876.72",Last updated as of 2025-05-31 02:11:27（UTC+0）,2025-05-31 09:12:40,1,None
3,"₫2,089,727,985,289,803","₫2,089,727,985,289,803","₫111,355,390,720,967.84",5.32%,"₫4,313,381.3","₫3,978,935.54","₫7,658,989.48","₫13,145.81","522,293,250 SOL","601,973,901.32SOL",...,"₫102,582,352.69","₫15,018,969.83",So1111...1111111(Solana)More,,solana,"₫4,001,062.53",Last updated as of 2025-05-31 02:11:31（UTC+0）,2025-05-31 09:12:40,1,None
4,"₫3,237,470,468,492,817.5","₫3,237,470,468,492,817.5","₫91,272,914,249,000.8",2.81%,"₫58,019.99","₫54,925.57","₫99,972.42",₫72.92,"58,759,725,000 XRP","99,986,084,900XRP",...,"₫911,816.26","₫133,498.02",0x1d2f...6c60dbe(BNB Smart Chain (BEP20))More,,ripple,"₫55,096.76",Last updated as of 2025-05-31 02:11:35（UTC+0）,2025-05-31 09:12:40,1,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
85,"₫618,002,295,562,013.5","₫618,002,295,562,013.5","₫23,609,991,415,225.17",3.82%,"₫18,569.72","₫17,453.22","₫80,644.97",₫451.58,"35,337,744,000 ADA","44,994,501,828.19ADA",...,"₫1,514,127.98","₫222,147.03",0x3ee2...d435d47(BNB Smart Chain (BEP20))More,,cardano,"₫17,488.45",Last updated as of 2025-05-31 02:57:48（UTC+0）,2025-05-31 09:58:12,9,None
86,"₫219,779,628,563,526.34","₫219,779,628,563,526.34","₫14,402,096,591,710.04",6.55%,"₫568,940.76","₫519,658.95","₫3,804,784.36","₫72,568.88","421,495,000 AVAX","456,497,710.58AVAX",...,"₫126,943,055.68","₫18,624,596.31",FvwEAh...GCgxN5Z(Avalanche X-Chain)More,,avalanche,"₫521,428.76",Last updated as of 2025-05-31 02:57:53（UTC+0）,2025-05-31 09:58:12,9,None
87,"₫163,298,251,774,159.78","₫163,298,251,774,159.78","₫7,566,746,256,066.08",4.63%,"₫110,024.07","₫102,291.46","₫1,431,303.02","₫70,072.75","1,582,695,800 DOT","1,582,695,840.59DOT",...,"₫33,806,789.36","₫4,960,001.96",0x7083...c873402(BNB Smart Chain (BEP20))More,,polkadot,"₫103,177.28",Last updated as of 2025-05-31 02:57:57（UTC+0）,2025-05-31 09:58:12,9,None
88,"₫232,696,936,801,412.6","₫232,696,936,801,412.6","₫15,588,491,452,694.54",6.69%,"₫383,807.06","₫353,531.99","₫1,375,906.61","₫3,286.42","657,099,970 LINK","1,000,000,000LINK",...,"₫81,427,284.72","₫11,946,697.66",0xf97f...8539FB4(Arbitrum)More,,chainlink,"₫354,127.15",Last updated as of 2025-05-31 02:58:00（UTC+0）,2025-05-31 09:58:12,9,None
89,"₫653,075,975,331,298.6","₫653,075,975,331,298.6","₫21,144,153,720,529.72",3.23%,"₫7,110.09","₫6,859.14","₫11,466.95",₫28.4,"94,866,360,000 TRX","94,866,348,630.1TRX",...,"₫564,013.07","₫82,749.83",0xCE7d...C6b12e3(BNB Smart Chain (BEP20))More,,tron,"₫6,884.17",Last updated as of 2025-05-31 02:58:04（UTC+0）,2025-05-31 09:58:12,9,None